
bool tracking_enabled

bool classifier_running
bool targeting_running

string image_topic
bool use_live_image
bool use_last_image

string[] available_classes_list
string selected_class
bool target_detected

string pantilt_device
string pantilt_connected
bool has_position_feedback
float32[] tilt_min_max_deg
float32[] pan_min_max_deg
float32 max_scan_time_sec
float32 scan_time_sec
float32 min_area_ratio
float32 scan_speed_ratio
float32 scan_tilt_offset
float32 scan_pan_angle
float32 track_speed_ratio
float32 track_tilt_offset

float32[] error_goal_min_max_deg
float32 error_goal_deg

bool is_scanning
bool is_tracking



