bool classifier_running
bool targeting_running
bool tracking_enabled

string classifier_name
string classifier_state
string classifier_connected

string image_topic
bool use_live_image
bool use_last_image

string[] available_classes_list
string selected_class
bool target_detected

string pantilt_device
string pantilt_connected
bool has_position_feedback
float32 min_area_ratio
float32 scan_speed_ratio
float32 scan_tilt_offset
float32 scan_pan_angle
float32 track_speed_ratio
float32 track_tilt_offset

bool is_running
bool is_scanning
bool is_tracking

float32[] xy_error_degs


